networks:
  default:
    name: roboshop
    driver: bridge
    external: true

services:
  mongodb:
    image: rajesh0525/mongodb:v1
    container_name: mongodb
  catalogue:
    image: rajesh0525/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: rajesh0525/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: rajesh0525/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
      image: rajesh0525/mysql:v1
      container_name: mysql

  shipping:
    image: rajesh0525/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  payment:
    image: rajesh0525/payment:v1
    container_name: payment
    environment:
      CART_HOST: CART
      CART_PORT: 8080
      USER_HOST: USER
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
      - rabbitmq
      - user
      - cart
  frontend:
    image: rajesh0525/frontend:v1
    container_name: frontend
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
    ports:
      - "80:80"

    